### ISSUE TITLE
It doesn't turn on in my PC

### ISSUE THREAD

**Issue by ProbiusPrime** [Haoming02/Unity-Assets-Utils#1]
https://github.com/Haoming02/Unity-Assets-Utils/assets/89365323/b9c02f7f-7202-43c1-896a-a64a424a06fb

Please refer to the uploaded video.
The program runs and is shut down immediately.
I can't think of cause.

**Comment by Haoming02** [comment]
Hmm. Could be missing .NET runtime.

The release was built on .NET 6
